### ISSUE TITLE
Rename to differentiate from the official Liferay CLI (liferay/liferay-cli)

### ISSUE THREAD

**Issue by slemarchand** [lgdd/lfr-cli#14]
Because the [liferay/liferay-cli ](https://github.com/liferay/liferay-cli )repository exists with the same name, it can be confusing. Some people could think lgdd/liferay-cli is a fork of liferay/liferay-cli.

So, to to give this repository the visibility and traction it deserves, it might be appropriate to rename it.

Below some random suggestions:
| Repository Name              | Command name | Notes |
| :---------------- | :------ | :---- |
| lfr-cli       |   lfr| Minimal change |
| unofficial-liferay-cli       |   lfr| Self-explanatory |
| rebel-liferay-cli       |   lfr| May the force be with you |
| yaalc          |   yaalc      | **Y**et **A**nother **A**wesome **L**iferay **C**LI |
| lpm-cli   |  lpm   | **L**iferay **P**rojects **M**anager  |
| lfrpm-cli   |  lfrpm   | **L**i**f**e**r**ay **P**rojects **M**anager  |
| lala-cli   |  lala   | **L**imitless  **A**mazing  **L**iferay **A**ssistant  |

**Comment by lgdd** [comment]
Thanks @slemarchand! I love all your ideas, and I think I'll go for the minimal change :)
